S_START = "0"  # Начало нового диалога или значение по умолчанию
S_MENU = "1"
S_MENU_ADMIN = "2"
S_TOP_UP_WALLET_USDT = "3"
S_EMAIL = "4"
S_USERNAME = "5"
S_TOP_UP_WALLET_ADMIN = "6"
S_TOP_UP_WALLET_USDT_ADMIN = "7"
S_TOP_UP_WALLET_METAMASK = "8"