# Generated by Django 3.2.13 on 2022-06-07 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_alter_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='P2p',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('timestamp', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('usdt_lkr', models.FloatField(default=0)),
                ('uah_usdt', models.FloatField(default=0)),
                ('eur_revolut_usdt', models.FloatField(default=0)),
                ('rub_tinkoff_usdt', models.FloatField(default=0)),
                ('usd_tinkoff_usdt', models.FloatField(default=0)),
                ('kzt_usdt', models.FloatField(default=0)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_of_use_user', models.TextField(blank=True, null=True)),
                ('terms_of_use_merchant', models.TextField(blank=True, null=True)),
                ('size_fee', models.FloatField(default=0)),
                ('filter_order_size_adminig', models.FloatField(default=300)),
                ('last_time_payment', models.PositiveBigIntegerField(default=1651688047000)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='message_id',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='ref_id',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='0', max_length=32),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('summ_invoice', models.FloatField(primary_key=True, serialize=False)),
                ('payer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payer_id_invoice_set', to='tgbot.user')),
            ],
        ),
    ]
