# Generated by Django 3.2.13 on 2022-06-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_auto_20220607_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
