# Generated by Django 3.2.12 on 2022-04-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_p2p'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2p',
            name='usd_tinkoff_usdt',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
