# Generated by Django 3.2.13 on 2022-06-16 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0006_alter_user_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Сourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('teaser', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('button_name', models.CharField(max_length=256)),
                ('callback_text', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Tarifs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_offer', models.CharField(max_length=256)),
                ('offer_code', models.CharField(max_length=256)),
                ('button_buy_name', models.CharField(max_length=256)),
                ('callback_text', models.CharField(max_length=256)),
                ('coast', models.FloatField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='сourse_tarifs_set', to='tgbot.сourses')),
            ],
        ),
    ]
