# Generated by Django 3.2.12 on 2022-04-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0006_auto_20220407_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='0', max_length=8),
        ),
    ]
