# Generated by Django 3.2.13 on 2022-06-16 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0007_tarifs_сourses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tarifs',
            new_name='Tarif',
        ),
        migrations.RenameModel(
            old_name='Сourses',
            new_name='Сourse',
        ),
    ]
