# Generated by Django 3.2.12 on 2022-04-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0007_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='merchant_client',
            field=models.CharField(default='0', max_length=8),
        ),
        migrations.AddField(
            model_name='user',
            name='orders_client',
            field=models.CharField(default='0', max_length=8),
        ),
    ]
