# Generated by Django 3.2.12 on 2022-04-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0008_auto_20220408_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('ru_name', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
    ]
