# Generated by Django 3.2.13 on 2022-06-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0008_auto_20220616_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='execute_selected_time',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
