# Generated by Django 3.2.13 on 2022-08-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0009_user_execute_selected_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_month',
            field=models.BooleanField(default=False),
        ),
    ]
