# Generated by Django 3.2.12 on 2022-04-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0010_auto_20220409_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pairs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(blank=True, max_length=32, null=True)),
                ('ru_pair', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
    ]
