# Generated by Django 3.2.12 on 2022-04-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0012_auto_20220409_0856'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Citis',
            new_name='Citys',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='citi',
            new_name='city',
        ),
    ]
