# Generated by Django 3.2.13 on 2022-08-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0012_user_remind'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bonus_programm',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
