# Generated by Django 3.2.13 on 2022-08-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0013_user_bonus_programm'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='execute_bonus_time',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
