# Generated by Django 3.2.12 on 2022-04-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0013_auto_20220409_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(blank=True, max_length=100, null=True)),
                ('ru_period', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
