# Generated by Django 3.2.12 on 2022-04-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0014_periods'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='message_id',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
