# Generated by Django 3.2.15 on 2022-08-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0014_user_execute_bonus_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='addr',
            field=models.CharField(default='0', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='addr_hex',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='private_key',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='public_key',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
