# Generated by Django 3.2.12 on 2022-04-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0015_user_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citys',
            name='id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pairs',
            name='id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='periods',
            name='id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
    ]
