# Generated by Django 3.2.12 on 2022-04-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0016_auto_20220409_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='period',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
