# Generated by Django 3.2.15 on 2022-08-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0016_auto_20220822_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='marker',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
