# Generated by Django 3.2.12 on 2022-04-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0017_user_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='merchant_client',
            field=models.CharField(default='None', max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='orders_client',
            field=models.CharField(default='None', max_length=8),
        ),
    ]
