# Generated by Django 3.2.15 on 2022-10-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0018_user_metamask_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='animoca_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='consensys_80_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='fanzee_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='kraken_36_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='kraken_45_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='spacex_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='true_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='twt_balance',
            field=models.FloatField(default=0),
        ),
    ]
