# Generated by Django 3.2.12 on 2022-04-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0018_auto_20220409_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='merchant_status',
            field=models.CharField(default='None', max_length=8),
        ),
    ]
