# Generated by Django 3.2.16 on 2023-01-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0020_user_animoca_2_4_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='addr_ton',
            field=models.CharField(default='0', max_length=256),
        ),
    ]
