# Generated by Django 3.2.12 on 2022-04-10 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0022_auto_20220410_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank', models.IntegerField(null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('who_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_id_rating_set', to='tgbot.user')),
                ('whom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whom_id_rating_set', to='tgbot.user')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
