# Generated by Django 3.2.12 on 2022-04-10 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0023_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_time',
            new_name='date_time_execut',
        ),
    ]
