# Generated by Django 3.2.12 on 2022-04-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0025_citys_convert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citys',
            name='convert',
        ),
        migrations.AddField(
            model_name='pairs',
            name='convert',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
