# Generated by Django 3.2.12 on 2022-04-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0028_order_status_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='merchant_status',
            field=models.CharField(default='pause', max_length=8),
        ),
    ]
