# Generated by Django 3.2.12 on 2022-04-10 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0029_alter_user_merchant_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantsCitys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_merchant_ids_set', to='tgbot.citys')),
                ('merchant_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_id_citys_set', to='tgbot.user')),
            ],
        ),
    ]
