# Generated by Django 3.2.12 on 2022-04-10 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0030_merchantscitys'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantsCities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='Citys',
            new_name='Cities',
        ),
        migrations.DeleteModel(
            name='MerchantsCitys',
        ),
        migrations.AddField(
            model_name='merchantscities',
            name='city_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_merchant_ids_set', to='tgbot.cities'),
        ),
        migrations.AddField(
            model_name='merchantscities',
            name='merchant_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_id_cities_set', to='tgbot.user'),
        ),
    ]
