# Generated by Django 3.2.12 on 2022-04-12 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0031_auto_20220410_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='status',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='merchant_executor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_executor_id_suggestion_set', to='tgbot.user'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='summ',
            field=models.FloatField(default=0),
        ),
    ]
