# Generated by Django 3.2.12 on 2022-04-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0034_auto_20220415_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='count_client_order',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='count_client_order_success',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='count_merchant_order',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='count_merchant_order_success',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
