# Generated by Django 3.2.12 on 2022-05-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0035_auto_20220418_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='terms',
            name='filter_order_size_adminig',
            field=models.FloatField(default=300),
        ),
    ]
