# Generated by Django 3.2.12 on 2022-05-04 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0036_terms_filter_order_size_adminig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('summ_invoice', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('payer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payer_id_invoice_set', to='tgbot.user')),
            ],
        ),
    ]
