# Generated by Django 3.2.12 on 2022-05-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0037_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='summ_invoice',
            field=models.FloatField(primary_key=True, serialize=False),
        ),
    ]
