# Generated by Django 3.2.13 on 2022-05-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0038_alter_invoice_summ_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='terms',
            name='last_time_payment',
            field=models.PositiveBigIntegerField(default=1651688047000),
        ),
    ]
