# Generated by Django 3.2.13 on 2022-06-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0039_terms_last_time_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2p',
            name='kzt_usdt',
            field=models.FloatField(default=0),
        ),
    ]
