# Generated by Django 3.2.13 on 2022-06-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0040_p2p_kzt_usdt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='transfer',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
