# Generated by Django 3.2.13 on 2022-06-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0041_user_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transfer',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
