# Generated by Django 3.2.13 on 2022-06-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0043_auto_20220602_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='merchant_delivery',
            field=models.CharField(default='None', max_length=256),
        ),
    ]
