# Generated by Django 3.2.13 on 2022-06-02 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0045_alter_user_merchant_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='merchant_delivery',
        ),
    ]
